# Generated by Django 5.1.5 on 2025-01-18 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0002_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='description',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='users',
            field=models.ManyToManyField(related_name='domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domain',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('users', models.ManyToManyField(related_name='business_objectives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
