# Generated by Django 5.1.5 on 2025-01-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0004_remove_customuser_role_alter_businessobjective_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessobjective',
            name='users',
        ),
        migrations.AddField(
            model_name='businessobjective',
            name='icon',
            field=models.CharField(default='fas fa-bullseye', max_length=50),
        ),
    ]
