# Generated by Django 5.1.5 on 2025-01-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0005_companysize_remove_businessobjective_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_objectives',
            field=models.ManyToManyField(blank=True, to='alyawebapp.businessobjective'),
        ),
    ]
