# Generated by Django 5.1.5 on 2025-02-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0005_assistant_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
