# Generated by Django 5.1.5 on 2025-01-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0007_integration_userintegration'),
    ]

    operations = [
    ]
