# Generated by Django 5.1.5 on 2025-01-19 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0008_create_default_integrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userintegration',
            options={'ordering': ['integration__name']},
        ),
        migrations.RenameField(
            model_name='integration',
            old_name='icon',
            new_name='icon_class',
        ),
        migrations.RenameField(
            model_name='userintegration',
            old_name='is_active',
            new_name='enabled',
        ),
        migrations.RemoveField(
            model_name='userintegration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userintegration',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='integration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alyawebapp.domain'),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
