# Generated by Django 5.1.5 on 2025-01-20 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0009_alter_integration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userintegration',
            options={},
        ),
        migrations.AddField(
            model_name='userintegration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userintegration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
