# Generated by Django 5.1.5 on 2025-01-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyawebapp', '0010_alter_userintegration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
