from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from .views import get_hubspot_auth_url

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('compte/', views.compte, name='compte'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('chat/', views.chat_view, name='chat'),
    path('get-chat-history/', views.get_chat_history, name='get_chat_history'),
    path('get-conversation/<int:chat_id>/', views.get_conversation, name='get_conversation'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-domains/', views.update_domains, name='update_domains'),
    path('reset-domains/', views.reset_domains, name='reset_domains'),
    path('update-company-size/', views.update_company_size, name='update_company_size'),
    path('update-objectifs/', views.update_objectifs, name='update_objectifs'),
    path('update-integrations/', views.update_integrations, name='update_integrations'),
    path('get-user-integrations/<str:domain_name>/', views.get_user_integrations, name='get_user_integrations'),
    path('get-integrations/<str:domain_name>/', views.get_integrations, name='get_integrations'),
    path('update-integration-config/', views.update_integration_config, name='update_integration_config'),
    path('api/integration/<int:integration_id>/config/', views.get_integration_config, name='get_integration_config'),
    path('toggle-integration/', views.toggle_integration, name='toggle_integration'),
    path('get-integration-config/<int:integration_id>/', views.get_integration_config, name='get_integration_config'),
    path('save-integration-config/', views.save_integration_config, name='save_integration_config'),
    path('test-integration/<int:integration_id>/', views.test_integration, name='test_integration'),
    path('integrations/hubspot/oauth/', views.hubspot_oauth, name='hubspot_oauth'),
    path('integrations/hubspot/callback/', views.hubspot_callback, name='hubspot_callback'),
    path('integration-success/', views.integration_success, name='integration_success'),
    path('get-user-integrations-state/', views.get_user_integrations_state, name='get_user_integrations_state'),
    path('clear-chat-history/', views.clear_chat_history, name='clear_chat_history'),
    path('get-messages/<int:chat_id>/', views.get_messages, name='get_messages'),
    path('get-hubspot-auth-url/', get_hubspot_auth_url, name='get_hubspot_auth_url'),
    path('integrations/trello/oauth/', views.trello_oauth, name='trello_oauth'),
    path('integrations/trello/callback/', views.trello_callback, name='trello_callback'),
    path('integrations/trello/save-token/', views.trello_save_token, name='trello_save_token'),
    path('integration/slack/oauth', views.slack_oauth, name="slack_oauth"),
    path('integration/slack/callback', views.slack_callback, name="slack_callback"),
    path('integration/gmail/oauth', views.gmail_oauth, name='gmail_oauth'),
    path('integration/gmail/callback', views.gmail_callback, name='gmail_callback'),
    path('integration/gdrive/oauth', views.google_drive_oauth, name='google_drive_oauth'),
    path('integration/gdrive/callback', views.google_drive_callback, name='google_drive_callback'),
    path('integration/mailchimp/oauth', views.mailchimp_oauth, name='mailchimp_oauth'),
    path('integration/mailchimp/callback', views.mailchimp_callback, name='mailchimp_callback'),
    path('integration/success/<str:integration_name>/', views.integration_success_view, name='integration_success'),
] 